name: Generate README from "generator" branch and push to "main" branch

on:
  schedule:
    - cron: "0 0 * * 0" # Sunday at 00:00 UTC
  workflow_dispatch:

jobs:
  GenerateAndPush:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Git clone the repository
        uses: actions/checkout@v4
        with:
          ref: generator # Branch name
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: npm ci
      - name: Generate README
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run generate
      - name: Push to "main" branch
        # https://github.com/orgs/community/discussions/26560
        run: |
          git fetch origin main
          git checkout main
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          cp ./generated/README.md ./README.md
          git add README.md
          git commit -m "Weekly update"
          git push origin main
